import logging
import os
from contextlib import asynccontextmanager
from typing import Optional

from fastapi import FastAPI, HTTPException, status, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Local imports
try:
    from agent import create_agent, run_config
    from agents import Runner, SQLiteSession
except ImportError as e:
    # Fallback for when running directly or if paths are messed up,
    # though in a proper env this shouldn't happen.
    logging.error(f"Failed to import agent modules: {e}")
    raise

# --- Configuration ---
class Settings:
    """Application configuration settings."""
    APP_NAME: str = "AI Agent API"
    APP_VERSION: str = "1.0.0"
    # Parse CORS origins from env var (comma-separated) or default to wildcard
    CORS_ORIGINS: list[str] = os.getenv("CORS_ORIGINS", "*").split(",")
    DB_PATH: str = "conversations.db"

settings = Settings()

# --- Logging Configuration ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("api")

# --- Application Initialization ---
app = FastAPI(
    title=settings.APP_NAME,
    description="Professional REST API for interacting with the RAG-enabled AI Agent.",
    version=settings.APP_VERSION,
    docs_url="/docs",
    redoc_url="/redoc"
)

# --- Middleware ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Data Models ---
class UserQuery(BaseModel):
    user: str = Field(
        ..., 
        min_length=1, 
        description="The user's natural language query.",
        example="What is the nervous system in robotics?"
    )
    session_id: str = Field(
        default="default_session",
        description="Unique identifier for the conversation session.",
        example="user_123_session"
    )

class AgentResponse(BaseModel):
    assistant: str = Field(..., description="The response generated by the AI agent.")
    status: str = Field(default="success", description="Response status.")

class HealthCheckResponse(BaseModel):
    status: str
    version: str

# --- Endpoints ---

@app.get(
    "/health", 
    response_model=HealthCheckResponse, 
    tags=["System"],
    status_code=status.HTTP_200_OK
)
async def health_check():
    """
    Perform a health check to verify the API is running.
    """
    return HealthCheckResponse(status="healthy", version=settings.APP_VERSION)

@app.post(
    "/agent", 
    response_model=AgentResponse, 
    tags=["Agent"],
    status_code=status.HTTP_200_OK,
    responses={
        500: {"description": "Internal Server Error - Agent execution failed"}
    }
)
async def run_agent(query: UserQuery):
    """
    Execute the AI agent with a user query.
    
    This endpoint initializes the agent, runs the query through the RAG pipeline,
    and returns the generated response. It uses SQLiteSession for persistent memory.
    """
    logger.info(f"Received agent query: {query.user} (Session: {query.session_id})")
    
    try:
        # Create a fresh agent instance for the request
        agent = create_agent()
        
        # Initialize the SQLite session
        # This will automatically load history for the given session_id
        session = SQLiteSession(
            session_id=query.session_id, 
            db_path=settings.DB_PATH
        )
        
        # Execute the agent runner with the session
        result = await Runner.run(
            starting_agent=agent,
            input=query.user,
            run_config=run_config,
            session=session
        )
        
        # Extract the final output
        response_text = str(result.final_output)
        
        logger.info("Agent execution completed successfully.")
        return AgentResponse(assistant=response_text)
        
    except Exception as e:
        logger.error(f"Error during agent execution: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while processing the request: {str(e)}"
        )
